services:
  wiremock:
    image: wiremock/wiremock:3.3.1
    container_name: mobile-onboarding-wiremock
    ports:
      - "8082:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    command: ["--global-response-templating", "--verbose"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

